training:
  method: CCMH
  dataName: Mirflickr25k
  batchSize: 64
  bit: 64
  cuda: True
  device: 0,1

datasetPath:
  Mirflickr25k:
    img_dir:  E:/hashing/datasets/mirflickr


dataPreprocess:
  img:
    resize: [224, 224]
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    toTensor: True
  txt:
    normalize:
      enable: False
  label:
    onehot: True

dataAugmentation:
  enable: True
  img:
    enable: True
    originalRetention: 0.2
    randomRotation:
      enable: True
      probability: 0.5
      rotationAngle: [[90, 90], [180, 180], [270, 270]]
    RandomHorizontalFlip:
      enable: True
      probability: 0.5
    RandomVerticalFlip:
      enable: True
      probability: 0.5
  txt:
    enable: False
    originalRetention: 0.5
    RandomErasure:
      enable: True
      probability: 0.2
      defaultValue: 0


